### ISSUE TITLE
Key Mapping and Installation question.

### ISSUE THREAD

**Issue by nr2003** [saubury/pi-peripheral#1]
Hi, What command do I run to install your software? I don't see an git clone or anything like that.
I only see create path commands etc, unless I am mistaken.

So If I wanted to do the following with no mod for alt, what would I use as a place holder?
(6, (KEY_S,MOD_ALT, KEY_S,MOD_L_CNTR))  # Switch 1

Thank you for your help in advance, It is much appreciated.

**Comment by saubury** [comment]
Yes, you'll need to clone to your Raspberry Pi

```
git clone https://github.com/saubury/pi-peripheral.git
cd pi-peripheral
```

If you want to specify a key press _without_ a modifier use `MOD_NONE`

**Comment by nr2003** [comment]
Alright, thank you.
